### ISSUE TITLE
*SAVE and *LOAD commands in BBC Basic incorrectly parse filenames

### ISSUE THREAD

**Issue by lennart-benschop** [breakintoprogram/cerberus-bbc-basic#2]

**Comment by lennart-benschop** [comment]
The command 
*SAVE filename.bin &F000 &800
creates the wrong filename with the other parameters inside.
*LOAD "filename.bin &F000 
tries to load the wrong filename.

**Comment by breakintoprogram** [comment]
Hi @lennart-benschop I think I've fixed that now - looking at the code I don't think that has ever worked.
